name: tsFly
main: club.tashhq.fly.Main
version: 1.0
api-version: 1.8
commands:
  fly:
    description: Toggle flight
    usage: /fly
  tsfly:
    description: Admin command for tsFly
    usage: /tsfly <toggle> <player>
permissions:
  tsfly.use:
    description: Allows toggling flight
    default: op
  tsfly.admin:
    description: Allows using admin features of tsFly
    default: op
